# syntax=docker/dockerfile:1
FROM python:3.8-alpine3.15
WORKDIR /app
COPY . .
RUN pip install --upgrade pip \
    && pip3 install -r requirements.txt \
    # this is for alpine to add new user
    && adduser -D myapp 
USER myapp
ENTRYPOINT [ "python" ]
CMD [ "-m" , "flask", "run", "--host=0.0.0.0"]