trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'my_dockerHub'
    repository: 'houseofus/py_test'
    command: 'buildAndPush'
    Dockerfile: '**/code/dockerfile'
    tags: '$(Build.BuildNumber)'
    addPipelineData: false
    addBaseImageData: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker system prune -af'